
    create table t_clyvo_animal (
        id_animal number(19,0) generated by default as identity,
        dt_nascimento date,
        especie varchar2(50 char),
        idade number(10,0),
        nm_animal varchar2(50 char),
        peso binary_double,
        raca varchar2(50 char),
        sexo varchar2(1 char),
        fk_id_responsavel number(19,0),
        primary key (id_animal)
    );

    create table t_clyvo_consulta (
        id_consulta number(19,0) generated by default as identity,
        dt_agendamento date,
        dt_consulta date not null,
        fk_id_animal number(19,0),
        fk_id_veterinario number(19,0),
        primary key (id_consulta)
    );
 
    create table t_clyvo_doenca (
        id_doenca number(19,0) generated by default as identity,
        contagiosidade varchar2(1 char),
        descricao clob,
        nm_doenca varchar2(50 char),
        tipo varchar2(50 char),
        primary key (id_doenca)
    );

    create table t_clyvo_doenca_animal (
        id_doenca_animal number(19,0) generated by default as identity,
        dt_diagnostico date,
        gravidade varchar2(50 char),
        observacoes clob,
        status varchar2(50 char),
        fk_id_animal number(19,0),
        fk_id_doenca number(19,0),
        primary key (id_doenca_animal)
    );

    create table t_clyvo_historico (
        id_historico number(19,0) generated by default as identity,
        dt_criacao_historico date,
        link_historico clob,
        num_consultas_clyvo binary_double,
        fk_id_animal number(19,0),
        fk_id_consulta number(19,0),
        primary key (id_historico)
    );
 
    create table t_clyvo_responsavel (
        id_responsavel number(19,0) generated by default as identity,
        cpf varchar2(14 char),
        dt_nascimento date,
        email varchar2(50 char) not null,
        nm_responsavel varchar2(50 char) not null,
        num_celular varchar2(20 char) not null,
        primary key (id_responsavel)
    );

    create table t_clyvo_swagger_pessoa (
        id number(19,0) generated by default as identity,
        cpf varchar2(255 char),
        data_nascimento date,
        email_pessoal varchar2(255 char),
        nome varchar2(60 char),
        primary key (id)
    );

    create table t_clyvo_swagger_user (
        id number(19,0) generated by default as identity,
        data_criacao date,
        permissao varchar2(255 char),
        senha varchar2(255 char),
        username varchar2(255 char),
        fk_pessoa number(19,0),
        primary key (id)
    );
 
    create table t_clyvo_vacina (
        id_vacina number(19,0) generated by default as identity,
        descricao clob,
        nm_vacina varchar2(50 char),
        tipo varchar2(50 char),
        primary key (id_vacina)
    );

    create table t_clyvo_vacina_animal (
        id_vacina_animal number(19,0) generated by default as identity,
        dt_receita date,
        frequencia_aplicacao number(10,0),
        num_doses number(10,0),
        fk_id_animal number(19,0),
        fk_id_vacina number(19,0),
        primary key (id_vacina_animal)
    );

    create table t_clyvo_veterinario (
        id_veterinario number(19,0) generated by default as identity,
        cpf varchar2(14 char),
        dt_nascimento date,
        email varchar2(50 char),
        especialidade varchar2(50 char) not null,
        nm_veterinario varchar2(50 char) not null,
        num_celular varchar2(20 char) not null,
        primary key (id_veterinario)
    );

    alter table t_clyvo_animal 
       add constraint FK4kjmpm6wddabhyg89tww5gfi1 
       foreign key (fk_id_responsavel) 
       references t_clyvo_responsavel;

    alter table t_clyvo_consulta 
       add constraint FKoiectva18xmm6f7yu2hl0wnn5 
       foreign key (fk_id_animal) 
       references t_clyvo_animal;

    alter table t_clyvo_consulta 
       add constraint FKlj611et5hdcgfxkgv9sy2nco8 
       foreign key (fk_id_veterinario) 
       references t_clyvo_veterinario;

    alter table t_clyvo_doenca_animal 
       add constraint FKpphornds4xnhlh8r5oy6fdp94 
       foreign key (fk_id_animal) 
       references t_clyvo_animal;

    alter table t_clyvo_doenca_animal 
       add constraint FKc90i9da99495kllhrh7ruijt4 
       foreign key (fk_id_doenca) 
       references t_clyvo_doenca;

    alter table t_clyvo_historico 
       add constraint FK9be4dsetbksitxvkdqhcfo8lb 
       foreign key (fk_id_animal) 
       references t_clyvo_animal;

    alter table t_clyvo_historico 
       add constraint FK52iwoe99cw1cw47ytpfu6ate2 
       foreign key (fk_id_consulta) 
       references t_clyvo_consulta;

    alter table t_clyvo_swagger_user 
       add constraint FK5bywmhqu4qvj1h7yajebesbx8 
       foreign key (fk_pessoa) 
       references t_clyvo_swagger_pessoa;

    alter table t_clyvo_vacina_animal 
       add constraint FKjc8bfoo6d4ijx4gkrmjsm68qj 
       foreign key (fk_id_animal) 
       references t_clyvo_animal;

    alter table t_clyvo_vacina_animal 
       add constraint FKmjgk7byold90oof9i537qtp37 
       foreign key (fk_id_vacina) 
       references t_clyvo_vacina;
       
INSERT INTO T_CLYVO_SWAGGER_PESSOA(nome, cpf, data_nascimento, email_pessoal) values('Pessoa 1','529.982.247-25', DATE '2002-05-05','pessoal1@gmail.com');

INSERT INTO T_CLYVO_SWAGGER_USER(fk_pessoa, username, senha, permissao, data_criacao) values(1,'RM1','$2a$10$0BhZzH8hG2FEW6qhs9UpV.XlaRPf.ODWDDevV67y3TzXeDzUUaRTK', 'USER', DATE '2026-05-05'); /*SENHA: 1234*/

INSERT INTO T_CLYVO_RESPONSAVEL (nm_responsavel, cpf, dt_nascimento, email, num_celular) VALUES ('Rodrigo Alves da Silva', '529.982.247-25', DATE '1995-01-01', 'rodrigo@gmail.com', '+55 (11) 99999-9999');

INSERT INTO T_CLYVO_RESPONSAVEL (nm_responsavel, cpf, dt_nascimento, email, num_celular) VALUES ('Amanda Ferreira Costa', '168.995.350-09', DATE '1998-07-20', 'amanda@gmail.com', '+55 (21) 98888-8888');

INSERT INTO T_CLYVO_VETERINARIO (nm_veterinario, cpf, dt_nascimento, email, num_celular, especialidade) VALUES ('Gabriel Martins', '295.379.148-06', DATE '1988-03-15', 'gabriel@gmail.com', '+55 (11) 97777-7777', 'Cardiologia');

INSERT INTO T_CLYVO_ANIMAL (nm_animal, idade, especie, raca, sexo, dt_nascimento, peso, fk_id_responsavel) VALUES ('Thor', 5, 'Cachorro', 'Golden Retriever', 'M', DATE '2021-03-10', 32, 1);

INSERT INTO T_CLYVO_DOENCA (nm_doenca, tipo, descricao, contagiosidade) VALUES ('Otite', 'Infecção', 'Infecção no ouvido', 'N');

INSERT INTO T_CLYVO_DOENCA_ANIMAL (dt_diagnostico, fk_id_animal, fk_id_doenca, gravidade, status, observacoes) VALUES (DATE '2026-05-10', 1, 1, 'Moderada', 'Em tratamento', 'Uso de antibiótico');

INSERT INTO T_CLYVO_CONSULTA (dt_agendamento, dt_consulta, fk_id_animal, fk_id_veterinario) VALUES (DATE '2026-05-09', DATE '2026-05-10', 1, 1);

INSERT INTO T_CLYVO_HISTORICO (dt_criacao_historico, num_consultas_clyvo, fk_id_animal, fk_id_consulta, link_historico) VALUES (DATE '2026-05-10', 1, 1, 1, 'https://historico-animal.com/1');

INSERT INTO T_CLYVO_VACINA (nm_vacina, tipo, descricao) VALUES ('V10', 'Canina', 'Vacina múltipla canina');

INSERT INTO T_CLYVO_VACINA_ANIMAL (num_doses, frequencia_aplicacao, dt_receita, fk_id_animal, fk_id_vacina) VALUES (3, 30, DATE '2026-05-01', 1, 1);

/* ================= RESPONSÁVEIS ================= */

INSERT INTO T_CLYVO_RESPONSAVEL
(nm_responsavel, cpf, dt_nascimento, email, num_celular)
VALUES
('Lucas Mendes Souza', '342.876.120-45', DATE '1990-04-14', 'lucas@gmail.com', '+55 (11) 98888-1111');

INSERT INTO T_CLYVO_RESPONSAVEL
(nm_responsavel, cpf, dt_nascimento, email, num_celular)
VALUES
('Fernanda Oliveira Lima', '987.654.321-88', DATE '1987-11-25', 'fernanda@gmail.com', '+55 (11) 97777-3333');


/* ================= VETERINÁRIOS ================= */

INSERT INTO T_CLYVO_VETERINARIO
(nm_veterinario, cpf, dt_nascimento, email, num_celular, especialidade)
VALUES
('Juliana Pereira', '123.456.789-10', DATE '1992-08-21',
'juliana@gmail.com', '+55 (11) 95555-5555', 'Dermatologia');

INSERT INTO T_CLYVO_VETERINARIO
(nm_veterinario, cpf, dt_nascimento, email, num_celular, especialidade)
VALUES
('Ricardo Gomes', '555.444.333-22', DATE '1985-02-10',
'ricardo@gmail.com', '+55 (11) 94444-4444', 'Ortopedia');


/* ================= ANIMAIS ================= */

INSERT INTO T_CLYVO_ANIMAL
(nm_animal, idade, especie, raca, sexo,
dt_nascimento, peso, fk_id_responsavel)
VALUES
('Luna', 3, 'Cachorro', 'Border Collie', 'F',
DATE '2023-02-15', 18.5, 2);

INSERT INTO T_CLYVO_ANIMAL
(nm_animal, idade, especie, raca, sexo,
dt_nascimento, peso, fk_id_responsavel)
VALUES
('Mingau', 2, 'Gato', 'Persa', 'M',
DATE '2024-01-12', 5.2, 3);

INSERT INTO T_CLYVO_ANIMAL
(nm_animal, idade, especie, raca, sexo,
dt_nascimento, peso, fk_id_responsavel)
VALUES
('Mel', 4, 'Cachorro', 'Shih Tzu', 'F',
DATE '2022-09-10', 8.7, 4);


/* ================= DOENÇAS ================= */

INSERT INTO T_CLYVO_DOENCA
(nm_doenca, tipo, descricao, contagiosidade)
VALUES
('Dermatite', 'Inflamação',
'Inflamação na pele do animal', 'N');

INSERT INTO T_CLYVO_DOENCA
(nm_doenca, tipo, descricao, contagiosidade)
VALUES
('Gripe Canina', 'Viral',
'Infecção respiratória em cães', 'S');


/* ================= DOENÇA ANIMAL ================= */

INSERT INTO T_CLYVO_DOENCA_ANIMAL
(dt_diagnostico, fk_id_animal, fk_id_doenca,
gravidade, status, observacoes)
VALUES
(DATE '2026-05-12', 2, 2,
'Leve', 'Em tratamento',
'Aplicação de pomada');

INSERT INTO T_CLYVO_DOENCA_ANIMAL
(dt_diagnostico, fk_id_animal, fk_id_doenca,
gravidade, status, observacoes)
VALUES
(DATE '2026-05-14', 3, 3,
'Moderada', 'Monitorando',
'Repouso e hidratação');


/* ================= CONSULTAS ================= */

INSERT INTO T_CLYVO_CONSULTA
(dt_agendamento, dt_consulta,
fk_id_animal, fk_id_veterinario)
VALUES
(DATE '2026-05-15', DATE '2026-05-16',
2, 2);

INSERT INTO T_CLYVO_CONSULTA
(dt_agendamento, dt_consulta,
fk_id_animal, fk_id_veterinario)
VALUES
(DATE '2026-05-17', DATE '2026-05-18',
3, 3);


/* ================= HISTÓRICOS ================= */

INSERT INTO T_CLYVO_HISTORICO
(dt_criacao_historico,
num_consultas_clyvo,
fk_id_animal,
fk_id_consulta,
link_historico)
VALUES
(DATE '2026-05-16',
2,
2,
2,
'https://historico-animal.com/2');

INSERT INTO T_CLYVO_HISTORICO
(dt_criacao_historico,
num_consultas_clyvo,
fk_id_animal,
fk_id_consulta,
link_historico)
VALUES
(DATE '2026-05-18',
1,
3,
3,
'https://historico-animal.com/3');


/* ================= VACINAS ================= */

INSERT INTO T_CLYVO_VACINA
(nm_vacina, tipo, descricao)
VALUES
('Antirrábica', 'Canina',
'Proteção contra raiva');

INSERT INTO T_CLYVO_VACINA
(nm_vacina, tipo, descricao)
VALUES
('V4', 'Felina',
'Múltipla felina');


/* ================= VACINA ANIMAL ================= */

INSERT INTO T_CLYVO_VACINA_ANIMAL
(num_doses,
frequencia_aplicacao,
dt_receita,
fk_id_animal,
fk_id_vacina)
VALUES
(1, 365, DATE '2026-05-15', 2, 2);

INSERT INTO T_CLYVO_VACINA_ANIMAL
(num_doses,
frequencia_aplicacao,
dt_receita,
fk_id_animal,
fk_id_vacina)
VALUES
(2, 30, DATE '2026-05-16', 3, 3);

COMMIT;

